# Generated by Django 5.1.4 on 2024-12-13 11:35

import auto_market.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('GEL', 'GEL')], max_length=3)),
                ('price_negotiable', models.BooleanField(default=False)),
                ('exchange_for_another_car', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=7)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DoorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DriveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GearType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('GE', 'Georgia'), ('SH', 'Shipping'), ('FR', 'Foreign'), ('OT', 'Other')], max_length=2)),
                ('flag', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MileageUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=2)),
                ('conversion_to_base', models.DecimalField(decimal_places=5, max_digits=5)),
                ('base_unit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SaloonColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=7)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SaloonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SteeringWheelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='CarMainFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('registration_month', models.PositiveIntegerField(blank=True, choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], null=True)),
                ('vin_code', models.CharField(blank=True, max_length=17)),
                ('engine_volume', models.DecimalField(decimal_places=2, help_text='Engine volume in liters (between 0.05 and 15 liters)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(15)])),
                ('turbo', models.BooleanField(default=False)),
                ('cylinders', models.PositiveIntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')])),
                ('mileage', models.PositiveIntegerField()),
                ('catalyst', models.BooleanField()),
                ('airbags', models.PositiveIntegerField(choices=[(0, '00'), (1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')])),
                ('description', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.carcategory')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.carmake')),
            ],
        ),
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cleared', models.BooleanField(default=False)),
                ('is_inspected', models.BooleanField(default=False)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('main_features', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car_listing.carmainfeatures')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('group_title', models.CharField(max_length=100)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.carmake')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.vehicletype')),
            ],
        ),
        migrations.AddField(
            model_name='carmainfeatures',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.carmodel'),
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='cars_photos/', validators=[auto_market.validators.validate_photo_size])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.carlisting')),
            ],
        ),
        migrations.AddField(
            model_name='carlisting',
            name='photos',
            field=models.ManyToManyField(blank=True, to='car_listing.carphoto'),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.carprice'),
        ),
        migrations.AddField(
            model_name='carmainfeatures',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.color'),
        ),
        migrations.AddField(
            model_name='carmainfeatures',
            name='doors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.dooroption'),
        ),
        migrations.AddField(
            model_name='carmainfeatures',
            name='drive_wheels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.drivetype'),
        ),
        migrations.AddField(
            model_name='carmainfeatures',
            name='features',
            field=models.ManyToManyField(blank=True, to='car_listing.feature'),
        ),
        migrations.AddField(
            model_name='carmainfeatures',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.fueltype'),
        ),
        migrations.AddField(
            model_name='carmainfeatures',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.geartype'),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_listing.location'),
        ),
        migrations.AddField(
            model_name='carmainfeatures',
            name='mileage_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.mileageunit'),
        ),
        migrations.AddField(
            model_name='carmainfeatures',
            name='saloon_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.salooncolor'),
        ),
        migrations.AddField(
            model_name='carmainfeatures',
            name='saloon_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.saloonmaterial'),
        ),
        migrations.AddField(
            model_name='carmainfeatures',
            name='steering_wheel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.steeringwheeltype'),
        ),
        migrations.AddField(
            model_name='steeringwheeltype',
            name='vehicle_type',
            field=models.ManyToManyField(related_name='gear_type', to='car_listing.vehicletype'),
        ),
        migrations.AddField(
            model_name='carmake',
            name='vehicle_types',
            field=models.ManyToManyField(related_name='car_make', to='car_listing.vehicletype'),
        ),
        migrations.AddField(
            model_name='carcategory',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.vehicletype'),
        ),
    ]
