# Generated by Django 5.1.4 on 2024-12-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileageunit',
            name='conversion_to_base',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
    ]
