# Generated by Django 5.1.4 on 2024-12-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0002_alter_mileageunit_conversion_to_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carprice',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
