# Generated by Django 5.1.4 on 2024-12-14 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0003_alter_carprice_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlisting',
            name='photos',
        ),
    ]
