# Generated by Django 5.1.4 on 2024-12-16 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0005_emailconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carphoto',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='car_listing.carlisting'),
        ),
    ]
