# Generated by Django 5.1.4 on 2024-12-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0006_alter_carphoto_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfirmation',
        ),
    ]
