# Generated by Django 5.1.4 on 2024-12-17 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_attachment_alter_message_content_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='attachment',
        ),
    ]
