# Generated by Django 5.1.4 on 2024-12-17 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_remove_message_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='last_updated',
        ),
    ]
