# Generated by Django 5.1.4 on 2024-12-17 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_chat_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
