# Generated by Django 5.1.4 on 2024-12-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_alter_chat_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
