# Generated by Django 5.1.4 on 2024-12-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_chat_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_update2',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
