# Generated by Django 5.1.4 on 2024-12-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_chat_last_update2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='last_update2',
        ),
    ]
